// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_P-HwWHAFIqMsqaIrOvsTse_UtGBr42g',
    appId: '1:628903137861:web:65ca134ba7b8741667092c',
    messagingSenderId: '628903137861',
    projectId: 'grad-7c2ae',
    authDomain: 'grad-7c2ae.firebaseapp.com',
    storageBucket: 'grad-7c2ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoJWuGiqzwl0TdTGtu5ejHhvcOJ1gQ8Kg',
    appId: '1:628903137861:android:927cb3dc38fa629f67092c',
    messagingSenderId: '628903137861',
    projectId: 'grad-7c2ae',
    storageBucket: 'grad-7c2ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_rxiIZDaSg6W-85tMgg1bIVI6S4irMho',
    appId: '1:628903137861:ios:cde2a497130e835f67092c',
    messagingSenderId: '628903137861',
    projectId: 'grad-7c2ae',
    storageBucket: 'grad-7c2ae.firebasestorage.app',
    iosBundleId: 'com.example.ru2ya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_rxiIZDaSg6W-85tMgg1bIVI6S4irMho',
    appId: '1:628903137861:ios:cde2a497130e835f67092c',
    messagingSenderId: '628903137861',
    projectId: 'grad-7c2ae',
    storageBucket: 'grad-7c2ae.firebasestorage.app',
    iosBundleId: 'com.example.ru2ya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_P-HwWHAFIqMsqaIrOvsTse_UtGBr42g',
    appId: '1:628903137861:web:78ea6d04b3f226d667092c',
    messagingSenderId: '628903137861',
    projectId: 'grad-7c2ae',
    authDomain: 'grad-7c2ae.firebaseapp.com',
    storageBucket: 'grad-7c2ae.firebasestorage.app',
  );
}
